export  const response = {
    status: 200,
    statusText: "OK",
    headers: {
      date: "Mon, 03 Apr 2023 02:41:20 GMT",
      "content-type": "application/json",
      "content-length": "611",
      connection: "close",
      "access-control-allow-origin": "*",
      "cache-control": "no-cache, must-revalidate",
      "openai-model": "text-davinci-003",
      "openai-organization": "nowstark",
      "openai-processing-ms": "2882",
      "openai-version": "2020-10-01",
      "strict-transport-security": "max-age=15724800; includeSubDomains",
      "x-ratelimit-limit-requests": "3000",
      "x-ratelimit-limit-tokens": "250000",
      "x-ratelimit-remaining-requests": "2999",
      "x-ratelimit-remaining-tokens": "249850",
      "x-ratelimit-reset-requests": "20ms",
      "x-ratelimit-reset-tokens": "36ms",
      "x-request-id": "f92a9a969b435ef69b87a24c5f634b17",
      "cf-cache-status": "DYNAMIC",
      server: "cloudflare",
      "cf-ray": "7b1df3a6fafeda7b-MIA",
      "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400",
    },
    data: {
      id: "cmpl-714QAIFy6qqFQsuM62kUHFRZcgwoU",
      object: "text_completion",
      created: 1680489678,
      model: "text-davinci-003",
      choices: [
        {
          text: "\n  filename: subscription.router.js\n  code:\n  ---\n  const express = require('express');\n  const router = express.Router();\n  const subscriptionController = require('../controllers/subscriptionController');\n\n  // CREATE a new subscription\n  router.post('/', subscriptionController.createSubscription);\n\n  module.exports = router;\n  ---",
          index: 0,
          logprobs: null,
          finish_reason: "stop",
        },
      ],
      usage: {
        prompt_tokens: 980,
        completion_tokens: 87,
        total_tokens: 1067,
      },
    },
  }